name: 'Test Report'
on:
  workflow_run:
    workflows: ['Android CI']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: JUnit Tests            # Name of the check run which will be created
        path: '*.xml'    # Path to test results
        reporter: java-junit        # Format of test results